Repository ZolaApp/zola-api, pull requests merged in 2018-04, with the labels that each got.

#4 Setup Express
  .babelrc
  .eslintignore
  .flowconfig
  .gitignore
  .vscode/settings.json
  bin/zola-dev.sh
  docker-compose.yml
  flow-typed/npm/body-parser_v1.x.x.js
  flow-typed/npm/express_v4.16.x.js
  package-lock.json
  package.json
  src/index.js
Labels: Feature, WIP

#5 Add babel aliases
  .babelrc
  .flowconfig
  package-lock.json
  package.json
  src/index.js
  src/routes/index.js
Labels: Feature

#18 Add helmet dependency for security
  flow-typed/npm/helmet_v3.x.x.js
  package-lock.json
  package.json
  src/server/index.js
Labels: Feature

#6 Setup Knex
  .babelrc
  .env.dist
  bin/zola-dev.sh
  docker-compose.yml
  index.js
  jsconfig.json
  package-lock.json
  package.json
  src/index.js
  src/models/User.js
  src/routes/index.js
  src/server/database/index.js
  src/server/database/knexfile.js
  src/server/database/migrations/20180413104019_create-users.js
  src/server/index.js
  src/server/routes/index.js
Labels: Feature

#20 Add `createUser` mutation
  .babelrc
  flow-typed/npm/babel-plugin-inline-import-graphql-ast_vx.x.x.js
  flow-typed/npm/bcrypt_vx.x.x.js
  flow-typed/npm/empty_vx.x.x.js
  flow-typed/npm/validator_vx.x.x.js
  flow-typed/npm/zxcvbn_vx.x.x.js
  jsconfig.json
  package-lock.json
  package.json
  src/api/User/index.js
  src/api/User/mutations/createUser/index.js
  src/api/User/mutations/createUser/validateEmail.js
  src/api/User/mutations/createUser/validatePassword.js
  src/api/User/queries/users.js
  src/api/schema/index.js
  src/api/schema/types/User.graphql
  src/api/schema/types/ValidationError.graphql
  src/models/User.js
  src/server/database/migrations/20180413104019_create-users.js
  src/server/index.js
  src/server/routes/index.js
  src/types/ValidationError.js
Labels: Feature

#21 Add tests for createUser mutation
  .eslintrc
  .gitignore
  flow-typed/npm/jest_v22.x.x.js
  flow-typed/npm/lodash_v4.x.x.js
  package-lock.json
  package.json
  src/api/User/mutations/createUser/helpers/validateEmail/index.js
  src/api/User/mutations/createUser/helpers/validateEmail/spec.js
  src/api/User/mutations/createUser/helpers/validatePassword/index.js
  src/api/User/mutations/createUser/helpers/validatePassword/spec.js
  src/api/User/mutations/createUser/index.js
  src/api/User/mutations/createUser/spec.js
  src/api/User/mutations/createUser/validatePassword.js
  src/api/schema/index.js
  src/models/User.js
  src/models/User/helpers/createUser/index.js
  src/models/User/helpers/createUser/spec.js
  src/models/User/index.js
  src/server/database/knexfile.js
  src/server/database/seeds/test/users.js
Labels: Testing

#17 Add helmet dependency for security and update all flow-typed definitions
  .babelrc
  flow-typed/npm/apollo-server-express_vx.x.x.js
  flow-typed/npm/babel-cli_vx.x.x.js
  flow-typed/npm/babel-eslint_vx.x.x.js
  flow-typed/npm/babel-plugin-add-module-exports_vx.x.x.js
  flow-typed/npm/babel-plugin-inline-import-graphql-ast_vx.x.x.js
  flow-typed/npm/babel-plugin-module-resolver_vx.x.x.js
  flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x.js
  flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js
  flow-typed/npm/bcrypt_vx.x.x.js
  flow-typed/npm/compression_vx.x.x.js
  flow-typed/npm/dotenv_vx.x.x.js
  flow-typed/npm/empty_vx.x.x.js
  flow-typed/npm/eslint-config-prettier_vx.x.x.js
  flow-typed/npm/eslint-config-standard_vx.x.x.js
  flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js
  flow-typed/npm/eslint-plugin-import_vx.x.x.js
  flow-typed/npm/eslint-plugin-node_vx.x.x.js
  flow-typed/npm/eslint-plugin-promise_vx.x.x.js
  flow-typed/npm/eslint-plugin-standard_vx.x.x.js
  flow-typed/npm/eslint_vx.x.x.js
  flow-typed/npm/flow-bin_v0.x.x.js
  flow-typed/npm/graphql-tools_vx.x.x.js
  flow-typed/npm/helmet_v3.x.x.js
  flow-typed/npm/husky_vx.x.x.js
  flow-typed/npm/knex_vx.x.x.js
  flow-typed/npm/lint-staged_vx.x.x.js
  flow-typed/npm/nodemon_vx.x.x.js
  flow-typed/npm/pg_v7.x.x.js
  flow-typed/npm/prettier_v1.x.x.js
  flow-typed/npm/validator_vx.x.x.js
  flow-typed/npm/zxcvbn_vx.x.x.js
  jsconfig.json
  package-lock.json
  package.json
  src/api/User/index.js
  src/api/User/mutations/createUser/index.js
  src/api/User/mutations/createUser/validateEmail.js
  src/api/User/mutations/createUser/validatePassword.js
  src/api/User/queries/users.js
  src/api/schema/index.js
  src/api/schema/types/User.graphql
  src/api/schema/types/ValidationError.graphql
  src/models/User.js
  src/server/database/migrations/20180413104019_create-users.js
  src/server/index.js
  src/server/routes/index.js
  src/types/ValidationError.js
Labels: Chore, Feature

#16 Add GraphQL setup
  .babelrc
  .flowconfig
  flow-typed/npm/apollo-server-express_vx.x.x.js
  flow-typed/npm/babel-cli_vx.x.x.js
  flow-typed/npm/babel-eslint_vx.x.x.js
  flow-typed/npm/babel-plugin-add-module-exports_vx.x.x.js
  flow-typed/npm/babel-plugin-inline-import-graphql-ast_vx.x.x.js
  flow-typed/npm/babel-plugin-module-resolver_vx.x.x.js
  flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x.js
  flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js
  flow-typed/npm/bcrypt_vx.x.x.js
  flow-typed/npm/compression_vx.x.x.js
  flow-typed/npm/dotenv_vx.x.x.js
  flow-typed/npm/empty_vx.x.x.js
  flow-typed/npm/eslint-config-prettier_vx.x.x.js
  flow-typed/npm/eslint-config-standard_vx.x.x.js
  flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js
  flow-typed/npm/eslint-plugin-import_vx.x.x.js
  flow-typed/npm/eslint-plugin-node_vx.x.x.js
  flow-typed/npm/eslint-plugin-promise_vx.x.x.js
  flow-typed/npm/eslint-plugin-standard_vx.x.x.js
  flow-typed/npm/eslint_vx.x.x.js
  flow-typed/npm/flow-bin_v0.x.x.js
  flow-typed/npm/graphql-tools_vx.x.x.js
  flow-typed/npm/helmet_v3.x.x.js
  flow-typed/npm/husky_vx.x.x.js
  flow-typed/npm/knex_vx.x.x.js
  flow-typed/npm/lint-staged_vx.x.x.js
  flow-typed/npm/lodash_v4.x.x.js
  flow-typed/npm/nodemon_vx.x.x.js
  flow-typed/npm/pg_v7.x.x.js
  flow-typed/npm/prettier_v1.x.x.js
  flow-typed/npm/validator_vx.x.x.js
  flow-typed/npm/zxcvbn_vx.x.x.js
  jsconfig.json
  package-lock.json
  package.json
  src/api/User/index.js
  src/api/User/mutations/createUser/index.js
  src/api/User/mutations/createUser/validateEmail.js
  src/api/User/mutations/createUser/validatePassword.js
  src/api/schema/index.js
  src/api/schema/types/Root.graphql
  src/api/schema/types/User.graphql
  src/api/schema/types/ValidationError.graphql
  src/constants/api.js
  src/models/User.js
  src/server/database/migrations/20180413104019_create-users.js
  src/server/index.js
  src/server/routes/index.js
  src/types/ValidationError.js
Labels: Feature

#27 Test createUser mutation
  .eslintrc
  .gitignore
  flow-typed/npm/jest_v22.x.x.js
  flow-typed/npm/lodash_v4.x.x.js
  package-lock.json
  package.json
  src/api/User/mutations/createUser/helpers/validateEmail/index.js
  src/api/User/mutations/createUser/helpers/validateEmail/spec.js
  src/api/User/mutations/createUser/helpers/validatePassword/index.js
  src/api/User/mutations/createUser/helpers/validatePassword/spec.js
  src/api/User/mutations/createUser/index.js
  src/api/User/mutations/createUser/spec.js
  src/api/User/mutations/createUser/validatePassword.js
  src/api/schema/index.js
  src/models/User.js
  src/models/User/helpers/createUser/index.js
  src/models/User/helpers/createUser/spec.js
  src/models/User/index.js
  src/server/database/knexfile.js
  src/server/database/seeds/test/users.js
Labels: Testing

#29 Move createUser validation from the mutation to the model’s method
  flow-typed/npm/pg_v7.x.x.js
  src/api/User/mutations/createUser/index.js
  src/api/User/mutations/createUser/integration.spec.js
  src/models/User/createUser/index.js
  src/models/User/createUser/integration.spec.js
  src/models/User/createUser/validations/validateEmail/index.js
  src/models/User/createUser/validations/validateEmail/unit.spec.js
  src/models/User/createUser/validations/validateName/index.js
  src/models/User/createUser/validations/validateName/unit.spec.js
  src/models/User/createUser/validations/validatePassword/index.js
  src/models/User/createUser/validations/validatePassword/unit.spec.js
  src/models/User/helpers/createUser/index.js
  src/models/User/helpers/createUser/integration.spec.js
  src/models/User/index.js
Labels: Refactoring, Testing

#33 Add padding-line-between-statements and import/order rule in eslint config
  .eslintrc
Labels: Chore

#39 Added Redis container
  .env.dist
  .gitignore
  docker-compose.yml
Labels: Chore

#38 Comply with user’s specs
  src/api/schema/index.js
  src/api/schema/scalars/Date.js
  src/api/schema/scalars/resolvers.js
  src/api/schema/scalars/scalars.graphql
  src/api/schema/types/User.graphql
  src/models/User/createUser/index.js
  src/models/User/createUser/validations/validatePassword/index.js
  src/models/User/index.js
  src/server/database/migrations/20180422151346_add-timestamp-users.js
  src/server/index.js
Labels: Feature

#41 Email validation
  .env.dist
  __mocks__/@sendgrid/mail.js
  docker-compose.yml
  flow-typed/npm/@sendgrid/mail_v6.x.x.js
  flow-typed/npm/redis-mock_vx.x.x.js
  flow-typed/npm/redis_v2.x.x.js
  package-lock.json
  package.json
  scripts/test.sh
  src/api/User/mutations/createUser/integration.spec.js
  src/api/schema/types/User.graphql
  src/constants/api.js
  src/constants/emails.js
  src/models/User/createUser/index.js
  src/models/User/createUser/integration.spec.js
  src/models/User/index.js
  src/models/User/sendValidationEmail/__mocks__/index.js
  src/models/User/sendValidationEmail/index.js
  src/models/User/sendValidationEmail/unit.spec.js
  src/server/database/knexfile.js
  src/server/database/migrations/20180424113807_add-validated-users.js
  src/server/index.js
  src/server/redis.js
  src/server/routes/validateEmail/index.js
  src/server/routes/validateEmail/integration.spec.js
  src/server/sendGrid.js
  src/tests/globalSetup.js
Labels: Feature

#48 Move some dependencies to devDependencies and run flow-typed install
  flow-typed/npm/apollo-cache-inmemory_vx.x.x.js
  flow-typed/npm/apollo-client_vx.x.x.js
  flow-typed/npm/apollo-link-schema_vx.x.x.js
  flow-typed/npm/apollo-server-express_vx.x.x.js
  flow-typed/npm/babel-cli_vx.x.x.js
  flow-typed/npm/babel-eslint_vx.x.x.js
  flow-typed/npm/babel-plugin-add-module-exports_vx.x.x.js
  flow-typed/npm/babel-plugin-inline-import-graphql-ast_vx.x.x.js
  flow-typed/npm/babel-plugin-module-resolver_vx.x.x.js
  flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x.js
  flow-typed/npm/babel-plugin-transform-flow-strip-types_vx.x.x.js
  flow-typed/npm/bcrypt_vx.x.x.js
  flow-typed/npm/compression_vx.x.x.js
  flow-typed/npm/dotenv_vx.x.x.js
  flow-typed/npm/empty_vx.x.x.js
  flow-typed/npm/eslint-config-prettier_vx.x.x.js
  flow-typed/npm/eslint-config-standard_vx.x.x.js
  flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js
  flow-typed/npm/eslint-plugin-import_vx.x.x.js
  flow-typed/npm/eslint-plugin-node_vx.x.x.js
  flow-typed/npm/eslint-plugin-promise_vx.x.x.js
  flow-typed/npm/eslint-plugin-standard_vx.x.x.js
  flow-typed/npm/eslint_vx.x.x.js
  flow-typed/npm/graphql-tools_vx.x.x.js
  flow-typed/npm/husky_vx.x.x.js
  flow-typed/npm/jest_v22.x.x.js
  flow-typed/npm/knex_vx.x.x.js
  flow-typed/npm/lint-staged_vx.x.x.js
  flow-typed/npm/nodemon_vx.x.x.js
  flow-typed/npm/validator_vx.x.x.js
  flow-typed/npm/zxcvbn_vx.x.x.js
  package-lock.json
  package.json
Labels: Chore

#47 Auth middleware first shot
  flow-typed/express_v4.x.x.js
  package-lock.json
  src/constants/api.js
  src/models/Token/createToken/index.js
  src/models/Token/index.js
  src/models/Token/retrieveToken/index.js
  src/models/Token/validateToken/index.js
  src/server/database/migrations/20180423122353_create-tokens.js
  src/server/index.js
  src/server/middlewares/auth.js
  src/server/routes/authRoutes.js
Labels: Feature

#50 Improved naming and added validate email path to the auth middleware whitelist
  .babelrc
  jsconfig.json
  package-lock.json
  src/api/User/mutations/createUser/integration.spec.js
  src/constants/api.js
  src/constants/routes.js
  src/database/index.js
  src/database/knexfile.js
  src/database/migrations/20180413104019_create-users.js
  src/database/migrations/20180422151346_add-timestamp-users.js
  src/database/migrations/20180423122353_create-tokens.js
  src/database/migrations/20180424113807_add-validated-users.js
  src/database/seeds/test/users.js
  src/models/Token/createToken/index.js
  src/models/Token/retrieveToken/index.js
  src/models/Token/validateToken/index.js
  src/models/User/createUser/index.js
  src/models/User/createUser/integration.spec.js
  src/server/index.js
  src/server/middlewares/auth.js
  src/server/routes/login.js
  src/server/routes/validateEmail/index.js
  src/server/routes/validateEmail/integration.spec.js
Labels: Improvement

#42 Add project entity and relations
  .babelrc
  jsconfig.json
  package-lock.json
  package.json
  scripts/dev.sh
  scripts/knex.sh
  src/api/Project/index.js
  src/api/Project/mutations/createProject/index.js
  src/api/Project/mutations/createProject/integration.spec.js
  src/api/ProjectUser/index.js
  src/api/ProjectUser/mutations/createProjectUser/index.js
  src/api/User/mutations/createUser/integration.spec.js
  src/api/schema/index.js
  src/api/schema/types/Project.graphql
  src/api/schema/types/ProjectUser.graphql
  src/api/schema/types/User.graphql
  src/database/migrations/20180423095250_create-projects.js
  src/database/migrations/20180423233147_create-projects_users.js
  src/database/seeds/test/users.js
  src/helpers/validateName/index.js
  src/helpers/validateName/unit.spec.js
  src/models/Project/createProject/index.js
  src/models/Project/index.js
  src/models/ProjectUser/createProjectUser/index.js
  src/models/ProjectUser/index.js
  src/models/Token/index.js
  src/models/User/createUser/index.js
  src/models/User/createUser/integration.spec.js
  src/models/User/createUser/validations/validateName/index.js
  src/models/User/index.js
  src/tests/resetDatabase.js
Labels: Feature, WIP

#62 Add status enum to API responses
  src/api/Project/mutations/createProject/index.js
  src/api/Project/mutations/createProject/integration.spec.js
  src/api/ProjectUser/mutations/createProjectUser/index.js
  src/api/User/mutations/createUser/index.js
  src/api/User/mutations/createUser/integration.spec.js
  src/api/schema/index.js
  src/api/schema/types/Project.graphql
  src/api/schema/types/ProjectUser.graphql
  src/api/schema/types/Status.graphql
  src/api/schema/types/User.graphql
  src/types/ValidationError.js
Labels: Feature

#63 Rework api directory structure and rename Status to ResponseStatus
  src/api/Project/index.js
  src/api/projects/index.js
  src/api/projects/mutations/createProject/index.js
  src/api/projects/mutations/createProject/integration.spec.js
  src/api/projects/mutations/createProjectUser/index.js
  src/api/schema/index.js
  src/api/schema/types/Project.graphql
  src/api/schema/types/ProjectUser.graphql
  src/api/schema/types/ResponseStatus.graphql
  src/api/schema/types/User.graphql
  src/api/users/index.js
  src/api/users/mutations/createUser/index.js
  src/api/users/mutations/createUser/integration.spec.js
Labels: Chore
