Repository ZolaApp/zola-api, pull requests merged in 2018-06, with the labels that each got.

#156 Fix locales not being loaded in the getProject query
  src/api/projects/queries/getProject/index.js
Labels: Bug

#159 Added default locale and strted working on locale stats
  src/api/projects/queries/getProject/index.js
  src/api/schema/types/Locale.graphql
  src/models/Locale/index.js
  src/models/Project/addLocaleToProject/index.js
Labels: Feature

#162 Add deleteTranslationKey mutation
  src/api/schema/types/TranslationKey.graphql
  src/api/translationKey/index.js
  src/api/translationKey/mutations/deleteTranslationKey/index.js
  src/database/migrations/20180521093455_create_translationKey_translationValue.js
  src/models/TranslationKey/deleteTranslationKey/index.js
Labels: Feature

#169 Add download route to CDN
  package-lock.json
  src/cdn/index.js
  src/server/index.js
Labels: Feature

#176 Set totalCount to 0 when no translation keys are found
  src/models/TranslationKey/getPaginatedTranslationKeys/index.js
Labels: Improvement

#175 Delete TranslationValue when passing an empty string and remove the validator
  src/api/schema/types/TranslationKey.graphql
  src/api/translationKey/mutations/addTranslationValueToTranslationKey/index.js
  src/models/TranslationValue/addTranslationValueToTranslationKey/index.js
Labels: Improvement

#180 Fix keys export
  src/cdn/index.js
  src/constants/routes.js
  src/models/TranslationKey/index.js
  src/server/index.js
Labels: Bug

#177 Translations prefilling when adding a new locale
  .env.dist
  package-lock.json
  package.json
  src/api/projects/mutations/addLocaleToProject/index.js
  src/api/schema/types/Project.graphql
  src/models/Project/addLocaleToProject/index.js
  src/models/Project/index.js
  src/models/TranslationKey/index.js
  src/models/TranslationValue/prefillTranslationsValues/index.js
Labels: Feature

#188 Add try catch around database operations and return a generic error
  package-lock.json
  src/api/users/mutations/loginUser/index.js
  src/models/TranslationKey/addTranslationKeyToProject/index.js
  src/models/TranslationValue/addTranslationValueToTranslationKey/index.js
  src/models/User/createUser/index.js
Labels: Improvement

#191 Send client error when the user tries to auto prefill a locale that we do not support
  src/models/TranslationValue/prefillTranslationsValues/index.js
  src/models/TranslationValue/prefillTranslationsValues/supportedLocales.js
Labels: Feature

#192 Add mutation to auto prefill a single translation value
  src/api/schema/types/TranslationKey.graphql
  src/api/translationKey/index.js
  src/api/translationKey/mutations/prefillTranslationValue/index.js
  src/helpers/autoTranslate/index.js
  src/helpers/autoTranslate/supportedLocales.js
  src/models/TranslationValue/addTranslationValueToTranslationKey/index.js
  src/models/TranslationValue/prefillTranslationValue/index.js
  src/models/TranslationValue/prefillTranslationsValues/index.js
Labels: Feature
