Repository ZolaApp/zola-api, pull requests merged in 2018-05, with the labels that each got.

#69 Adding config to connect to any redis host
  .env.dist
  src/server/redis.js
Labels: Chore

#64 Move validateName helper to a more generic validateString helper
  src/helpers/validateName/index.js
  src/helpers/validateName/unit.spec.js
  src/helpers/validateString/index.js
  src/helpers/validateString/unit.spec.js
  src/models/Project/createProject/index.js
  src/models/User/createUser/index.js
Labels: Refactoring

#76 Remove obsolete features with MVP rescoping
  package-lock.json
  scripts/dev.sh
  src/api/projects/index.js
  src/api/projects/mutations/createProject/integration.spec.js
  src/api/projects/mutations/createProjectUser/index.js
  src/api/schema/index.js
  src/api/schema/types/Project.graphql
  src/api/schema/types/ProjectUser.graphql
  src/database/migrations/20180423233147_create-projects_users.js
  src/models/Project/createProject/index.js
  src/models/Project/index.js
  src/models/ProjectUser/createProjectUser/index.js
  src/models/ProjectUser/index.js
Labels: Refactoring

#95 Remove email validation and all of its dependencies
  .env.dist
  .gitignore
  __mocks__/@sendgrid/mail.js
  docker-compose.yml
  flow-typed/npm/@sendgrid/mail_v6.x.x.js
  flow-typed/npm/apollo-cache-inmemory_vx.x.x.js
  flow-typed/npm/apollo-client_vx.x.x.js
  flow-typed/npm/babel-plugin-inline-import-graphql-ast_vx.x.x.js
  flow-typed/npm/graphql-tools_vx.x.x.js
  flow-typed/npm/jest_v22.x.x.js
  flow-typed/npm/knex_v0.14.x.js
  flow-typed/npm/knex_vx.x.x.js
  flow-typed/npm/lint-staged_vx.x.x.js
  flow-typed/npm/nodemon_vx.x.x.js
  flow-typed/npm/redis-mock_vx.x.x.js
  flow-typed/npm/redis_v2.x.x.js
  flow-typed/npm/validator_vx.x.x.js
  package-lock.json
  package.json
  src/api/schema/types/User.graphql
  src/api/users/mutations/createUser/integration.spec.js
  src/constants/api.js
  src/constants/emails.js
  src/constants/routes.js
  src/database/migrations/20180424113807_add-validated-users.js
  src/models/User/createUser/index.js
  src/models/User/createUser/integration.spec.js
  src/models/User/index.js
  src/models/User/sendValidationEmail/__mocks__/index.js
  src/models/User/sendValidationEmail/index.js
  src/models/User/sendValidationEmail/unit.spec.js
  src/server/index.js
  src/server/redis.js
  src/server/routes/validateEmail/index.js
  src/server/routes/validateEmail/integration.spec.js
  src/server/sendGrid.js
Labels: Refactoring

#68 Added tests for Token operations
  flow-typed/express_v4.x.x.js
  package-lock.json
  src/api/projects/mutations/createProject/index.js
  src/api/users/mutations/createUser/index.js
  src/models/Project/createProject/index.js
  src/models/Project/index.js
  src/models/Token/createToken/index.js
  src/models/Token/createToken/integration.spec.js
  src/models/Token/createToken/unit.spec.js
  src/models/Token/index.js
  src/models/Token/validateToken/index.js
  src/models/User/createUser/index.js
  src/models/User/index.js
  src/server/middlewares/auth.js
  src/server/routes/login.js
Labels: Testing

#85 Automatically retrieve ownerId from auth middleware when creating a project
  .babelrc
  .env.dist
  package-lock.json
  package.json
  src/api/projects/mutations/createProject/index.js
  src/api/projects/mutations/createProject/integration.spec.js
  src/api/schema/types/Project.graphql
  src/server/index.js
  src/tests/client.js
Labels: Improvement, WIP

#104 Show an error to the user when they try to create a project with a duplicate name
  package-lock.json
  package.json
  src/models/Project/createProject/index.js
  src/models/User/createUser/index.js
Labels: Improvement

#106 Add firstName, lastName and job fields to User
  src/api/schema/types/User.graphql
  src/api/users/mutations/createUser/integration.spec.js
  src/database/migrations/20180516205957_add-missing-users-fields.js
  src/database/seeds/test/users.js
  src/models/Project/createProject/index.js
  src/models/Project/index.js
  src/models/Token/index.js
  src/models/User/createUser/index.js
  src/models/User/createUser/integration.spec.js
  src/models/User/index.js
Labels: Feature

#110 Add missing passwordConfirmation arg to createUser mutation
  src/api/schema/types/User.graphql
  src/api/users/mutations/createUser/integration.spec.js
  src/database/seeds/test/users.js
  src/models/User/createUser/index.js
  src/models/User/createUser/integration.spec.js
Labels: Feature

#115 Improve import of Flow types
  src/api/projects/mutations/createProject/index.js
  src/api/users/mutations/createUser/index.js
  src/api/users/mutations/loginUser/index.js
  src/models/Project/createProject/index.js
  src/models/User/createUser/index.js
Labels: Improvement

#116 Fix incorrect passwordPlain field errors
  src/models/User/createUser/index.js
  src/models/User/createUser/integration.spec.js
Labels: Bug

#132 Use slug instead of id to retrieve a single project
  src/api/projects/queries/getProject/index.js
  src/api/schema/types/Project.graphql
Labels: Improvement

#120 TranslationKey and TranslationValue
  package-lock.json
  src/api/projects/index.js
  src/api/projects/mutations/addTranslationKeyToProject/index.js
  src/api/projects/queries/getProject/index.js
  src/api/schema/index.js
  src/api/schema/types/Project.graphql
  src/api/schema/types/TranslationKey.graphql
  src/api/schema/types/TranslationValue.graphql
  src/api/translationKey/index.js
  src/api/translationKey/mutations/addTranslationValueToTranslationKey/index.js
  src/constants/errors.js
  src/database/migrations/20180521093455_create_translationKey_translationValue.js
  src/models/Project/index.js
  src/models/TranslationKey/addTranslationKeyToProject/index.js
  src/models/TranslationKey/index.js
  src/models/TranslationValue/addTranslationValueToTranslationKey/index.js
  src/models/TranslationValue/index.js
Labels: Feature

#134 Expose timestamps in project schema
  src/api/schema/types/Project.graphql
Labels: Improvement
